### ISSUE TITLE
Convert a good number of regression tests to use cam_dev

### ISSUE THREAD

**Issue by cacraigucar** [ESCOMP/CAM#599] opened 2022-05-25 17:56 UTC
### Issue Type

Infrastructure Update

### Issue Description

Most tests are currently using CAM5 or CAM6, but cam_dev is becoming the workhorse model.  More CAM regression tests should use this physics package.

I propose that individual developers look at their current regression tests, and indicate which should be updated to cam_dev (keeping some still testing the older versions of CAM).    One of us will compile the changes and make the PR.

Also, it was pointed out that there are a number of use_cases in config components which are no longer being used and should be removed

### Will this change answers?

No

### Will you be implementing this yourself?

Yes, but I will need some help

**Comment by nusbaume** [comment] 2024-01-04 21:40
Closing this issue as it is now a duplicate of #258.

**Closed by nusbaume** 2024-01-04 21:40 UTC
Labels: enhancement, CoupledEval3
