### ISSUE TITLE
Zhang McFarlane (ZM) Convective Parcel Modification

### ISSUE THREAD

**Issue by swrneale** [ESCOMP/CAM#428] opened 2021-09-03 16:05 UTC
Include the new calculation of the convective parcel initialization properties and vertical level (in zm_conv.F90). This will form part of the prototype version of CAM7 with increased vertical resolution (L58 and L93 as of 9/3/2021).

**Comment by gold2718** [comment] 2021-09-07 17:26
Is this a duplicate of #383?

**Comment by swrneale** [comment] 2021-09-07 17:32
Why, yes it is, sorry. I clearly didn't search for it correctly. I'll close this one then.

**Comment by swrneale** [comment] 2021-09-07 17:33
Duplicate of  #383 so closing.

**Closed** 2021-09-07 17:32 UTC
Labels: enhancement
