### ISSUE TITLE
Divide-by-zero bug on cam_dev L58 grid when DEBUG=TRUE #543

### ISSUE THREAD

**Issue by bstephens82** [ESCOMP/CAM#543] opened 2022-03-18 06:36 UTC
While running some FHIST tests using CAM tag cam6_3_052, using CAM_CONFIG_OPTS="-phys cam_dev -nlev 58", I found that the model crashed at the first time step when run with DEBUG=TRUE, but runs successfully with the debugger turned off. According to the stack traceback, the line that was causing problems was (for me) line 4158 in zm_conv.F90, 
~~~
      hpar(i) = parcel_hdp(i)/parcel_dp(i)
~~~
What appears to be happening is `parcel_dp` is initialized to zero, and, while there's an `if` statement above this line that defines `parcel_dp`, this `if` statement isn't being triggered past a certain `i` index (looks like i=12 from my print statements), and so `parcel_dp` was left at zero, hence there's a divide by zero.

@cacraigucar adds:
>The executive summary is that I've confirmed this is a bug (and potentially a very important one to track down) and an issue should be opened for it.

>Some more clues:

>I was able to reproduce the error that Ben is seeing using the exact same setup he was using with a fresh clone from Kate's branch.

>I then removed the --nlev 58  in CAM_CONFIG_OPTS and the ncdata file in user_nl_cam.  With these two modifications, the job ran to completion (a 9 time step job).  This appears to be an error that is occurring only with the new levels.  That's why Rich and I didn't see it previously.

>I then went back to Ben's original failing job and simply removed the "DEBUG=true".  That too ran to completion (9 time steps).

>That said, I'm also concerned that perhaps all of the 58 level runs have a problem and because they are not being run in DEBUG=true mode, they are not being captured.  At the very least we should note that there is an issue with DEBUG=true as it is a problem which should be tracked down.

      Run using katec/new_clubb_cam6_3_052

      TABLE OF RUNS:    name                     cam_dev       nlev      debug       run status
             Run:       1 (Ben's run)               on          58         T         core dump (zm_conv.F90 line 4158)  
             Run:       2 (Cheryl's run)            on          58         T         core dump (zm_conv.F90 line 4158)
             Run:       3 (Cheryl's run)            on          32         T         runs 9 time steps
             Run:       4 (Cheryl's run)            on          58         F         runs 9 time steps
             Run:       5 (Cheryl's run)            off         58         T         runs 9 time steps

Also ran:

      Run using cam_development/cam6_3_053

      TABLE OF RUNS:    name                      cam_dev       nlev      debug      run status
             Run:       2_053 (Cheryl's run)        on          58         T         core dump (zm_conv.F90 line 4158)

**Comment by gold2718** [comment] 2022-03-18 15:21
What version of the code was used for these tests? We need a reproducible test at the head of cam_development.

**Comment by bstephens82** [comment] 2022-03-18 15:29
> What version of the code was used for these tests? We need a reproducible test at the head of cam_development.

The path to the code I was using is /glade/u/home/stepheba/CAM2/

**Comment by cacraigucar** [comment] 2022-03-18 15:40
I have verified (just now) that this test crashes when using cam6_3_053 with a floating point exception.  The commands to reproduce are:  

./create_newcase --case test --compset FHIST --res ne30pg3_ne30pg3_mg17 --driver mct --run-unsupported --pecount 1200 --queue premium
./xmlchange --id STOP_OPTION --val nsteps; ./xmlchange --id STOP_N --val 9; ./xmlchange CAM_CONFIG_OPTS="-phys cam_dev  -nlev 58"; ./xmlchange DEBUG=TRUE

user_nl_cam contains: 
ncdata = '/glade/p/cesm/amwg_dev/juliob/cam_ic_files/se_dycore/FWsc_ne30pg3_58L_GRID_48_taperstart10km_lowtop_BL10_v3_beta1p75_Top_43km.nc' now

I plan on next running without cam_dev, but keeping -nlev 58 and will report on those findings

**Comment by gold2718** [comment] 2022-03-18 15:45
I don't know how stable the 58 level model is stable without cam_dev, isn't that why Adam made the change?
@adamrher, is there a reason the default for cam_dev is 32 levels (130 for WACCM)? Should we bump it up to 58?

**Comment by adamrher** [comment] 2022-03-18 16:18
> We need a reproducible test at the head of cam_development.

I'm not sure if that's possible before Kate pushes in the new clubb externals. 

Some context. Ben was running Kate's branch w/ the new externals, but it was before she merged it up to the head, and so cam_dev wasn't available in those runs. He said it was crashing w/ L58, and I suggested he get Kate to merge to the head so that you can run w/ cam_dev. He found that that worked, provided DEBUG=F ... and that w/ DEBUG=T he gets the error described at the top of this thread.

@cacraigucar are you getting the same stack traceback as Ben is getting? Since you're not running prognostic momentum I don't understand how we didn't get this error in the past?

> Should we bump it up to 58?

That's the plan. But perhaps not a flaming hot priority since Cecile is mainly doing all the L58 runs and she just points to a L58 ncdata file in Julio's directory for now. But yeah, we will need to get that into the repo, and make L58 the default for cam_dev eventually. In the meantime there is nothing wrong w/ running cam_dev w/ L32 ... it's will only improve your solution by subduing 2dt wind oscillations in the lowest model leve.

**Comment by gold2718** [comment] 2022-03-18 16:42
> I'm not sure if that's possible before Kate pushes in the new clubb externals.

That's why I want the test. If it turns out that the bug only happens with the new CLUBB external, then it should either be fixed in that PR or after that PR (I vote for with the PR since the source of the issues seems to have already been identified).

**Comment by cacraigucar** [comment] 2022-03-18 16:54
> > I'm not sure if that's possible before Kate pushes in the new clubb externals.
> 
> That's why I want the test. If it turns out that the bug only happens with the new CLUBB external, then it should either be fixed in that PR or after that PR (I vote for with the PR since the source of the issues seems to have already been identified).

I'm not sure you folks saw the post I made an hour ago, but this fails with cam6_3_053 in the same way (no updated CLUBB external).  I will be amending the description with a table to help keep track of the various permutations to help narrow in on the problem.

**Comment by cacraigucar** [comment] 2022-03-18 16:56
> @cacraigucar are you getting the same stack traceback as Ben is getting? Since you're not running prognostic momentum I don't understand how we didn't get this error in the past?

The error seems to be tied to using 58 levels, debug and cam_dev.  I never ran with 58 levels and it works just fine with L32.

**Comment by gold2718** [comment] 2022-03-18 17:11
> The error seems to be tied to using 58 levels, debug and cam_dev. I never ran with 58 levels and it works just fine with L32.

I think we should modify the F2000dev test to have 58 levels. If you are correct, this will now crash and we have a better regression test.

**Comment by adamrher** [comment] 2022-03-18 17:16
@cacraigucar all clear now. this is not a clubb externals issue (if it's the exact same error Ben is getting)

> I think we should modify the F2000dev test to have 58 levels. If you are correct, this will now crash and we have a better regression test.

Then in that case, let's just have cam_dev default to L58 and point to Julio's ncdata file. Kill to birds w/ one stone as they say. I'd suggest not adding in an FV ncdata file for L58, and let the model bomb if someone tries to run FV w/ cam_dev.

**Comment by bstephens82** [comment] 2022-03-18 20:56
So, one thing I've found from print statements is that there are times when `parcel_ztop` is negative.  For example here is a block of output from a print statement placed just before the `if` statement in question:
>364: i, k, zi(i,k+1) parcel_ztop(i) =            2          58
>364:  0.000000000000000E+000  -2.28611574633487
>364: i, k, zi(i,k+1) parcel_ztop(i) =            2          57
>364:   39.5982121966120       -2.28611574633487
>364: i, k, zi(i,k+1) parcel_ztop(i) =            2          56
>364:   101.740819702489       -2.28611574633487
>364: i, k, zi(i,k+1) parcel_ztop(i) =            2          55
>364:   169.448314757602       -2.28611574633487
>364: i, k, zi(i,k+1) parcel_ztop(i) =            2          54
>364:   243.267920463673       -2.28611574633487

In this case, if `zi` is always greater than or equal to zero, the `if` statement will never be triggered.  `parcel_ztop` is set by these lines,
~~~
      pbl_z(i) = z(i,nint(pblt(i)))
      parcel_ztop(i) = 0.5_r8*pbl_z(i) ! 0.5*Boundary layer top by default
~~~
and as far as I can tell `pblt` is always equal to 58 in the tests I've done. So it seems as though `pbl_z(i,58)` must come out negative for some values of `i`.  I'll try some further tests to confirm this.

**Comment by swrneale** [comment] 2022-03-18 21:20
Even if pblt=58 pbl_z(i,58)should not go negative anywhere. Unless the dynamics vertical grid remapping is doing something very odd. pblt=58 is the default initial setting made in ZM which should work no problem as zi(58+1) will always be less that 0.5*z(58).

I'm wondering if you could run w/o the debugger for 2 timesteps and then see what the same set of points think the values look like also.

We could easily put a limiter to say that pbl_z is positive. But z should be positive anyway :).

Maybe we should speak to Peter to see how this could happen.

**Comment by bstephens82** [comment] 2022-03-18 21:30
Here is some additional output showing that `pbl_z(i,58)` is indeed going negative at a few times during the simulation.  Included here are the process number, lchnk, and pblt
364: iam, lchnk, pblt =          364           3   58.0000000000000
364:   58.0000000000000        58.0000000000000        58.0000000000000
364:   58.0000000000000        58.0000000000000        58.0000000000000
364:   58.0000000000000        58.0000000000000        58.0000000000000
364:   58.0000000000000        58.0000000000000        58.0000000000000
364:   58.0000000000000        58.0000000000000        58.0000000000000
364: pbl_z(           2 ) =   -4.57223149266974
364: pbl_z(           3 ) =   -1.62363685170075
364: pbl_z(           7 ) =   -1.60185491691292
364: pbl_z(          10 ) =   -1.81512617719907
364: pbl_z(          13 ) =  -0.730554486515654
364: pbl_z(          14 ) =   -5.13878612463700
The number in parentheses is `i`.  




> I'm wondering if you could run w/o the debugger for 2 timesteps and then see what the same set of points think the values look like also.

Sure I'll try this.

**Comment by swrneale** [comment] 2022-03-18 21:38
Thanks. So weird!
@PeterHjortLauritzen Could z(nlev) go negative in extreme remapping circumstances?

**Comment by bstephens82** [comment] 2022-03-18 22:05
@swrneale The subroutine gives the exact same negative numbers when DEBUG=FALSE:
364: pbl_z(           1 ) =    8.10881426577075
364: pbl_z(           2 ) =   -4.57223149266974
364: pbl_z(           3 ) =   -1.62363685170075
364: pbl_z(           4 ) =    14.5128194362766
364: pbl_z(           5 ) =    27.6583009622785
364: pbl_z(           6 ) =    8.23307428248256
364: pbl_z(           7 ) =   -1.60185491691292
364: pbl_z(           8 ) =    17.6207985445420
364: pbl_z(           9 ) =    6.13328108403924
364: pbl_z(          10 ) =   -1.81512617719907
364: pbl_z(          11 ) =    18.2101469792295
364: pbl_z(          12 ) =    6.91783408703219
364: pbl_z(          13 ) =  -0.730554486515651
364: pbl_z(          14 ) =   -5.13878612463700
364: pbl_z(          15 ) =    5.39271422812004
364: pbl_z(          16 ) =    41.2737852014352

**Comment by swrneale** [comment] 2022-03-18 22:07
@bstephens82 I guess I was wondering whether on the 2nd and successive timesteps the problem goes away.

**Comment by adamrher** [comment] 2022-03-18 22:14
> Here is some additional output showing that pbl_z(i,58) is indeed going negative at a few times during the simulation.

Weird that zi seems well behaved (i.e., zi(k=59)=0. from in ur earlier post) whereas z(k=58) must be less than zero to give pbl_z(k=58) < 0. That's a head scratcher ...

**Comment by bstephens82** [comment] 2022-03-18 22:15
Ah sorry @swrneale, yes it looks like subsequent print statements are more sensible.  This is the next print statement from process 364, lchnk 3:
364: pbl_z(           1 ) =    916.039473197065
364: pbl_z(           2 ) =    536.190829677722
364: pbl_z(           3 ) =    538.384101829396
364: pbl_z(           4 ) =    552.331827437056
364: pbl_z(           5 ) =    463.279815009880
364: pbl_z(           6 ) =    444.187215039224
364: pbl_z(           7 ) =    434.271977318837
364: pbl_z(           8 ) =    451.254116928291
364: pbl_z(           9 ) =    439.381258888965
364: pbl_z(          10 ) =    430.789882302473
364: pbl_z(          11 ) =    358.900692406823
364: pbl_z(          12 ) =    347.187481625615
364: pbl_z(          13 ) =    429.205940891416
364: pbl_z(          14 ) =    430.021979600556
364: pbl_z(          15 ) =    348.014685259958
364: pbl_z(          16 ) =    382.150244738576

**Comment by swrneale** [comment] 2022-03-18 22:28
That's good at least! zm and zi come directly from the state vector so anything could be changing that.

**Comment by adamrher** [comment] 2022-03-18 22:48
> That's good at least! zm and zi come directly from the state vector so anything could be changing that

Not that much though. This happens in phase 2 of the initialization; the dynamics haven't even been called yet. This is the first call to tphysbc. Maybe the initial conditions are wack? I wonder what happens if you set the ncdata file to a cam.i file from a run that went on a bit. You can try setting ncdata to this:

```
/glade/scratch/hannay/archive/f.e21.FWscHIST.ne30_L48_BL10_cam6_3_041_control.hf.001/atm/hist/f.e21.FWscHIST.ne30_L48_BL10_cam6_3_041_control.hf.001.cam.i.1990-01-01-00000.nc
```

**Comment by adamrher** [comment] 2022-03-18 22:57
another possibility is that @PeterHjortLauritzen and I found a "bug" in pg3 runs (it's a one line fix), with how we map from PHIS on dyn grid to the physgrid. Since the ncdata file is on the dyn grid, it could be related to this weird mapping issue. I know @PeterHjortLauritzen is probably out for the week, but making this note here to remind myself to look into this next week.

This L58 grid seem to really test our model!

**Comment by JulioTBacmeister** [comment] 2022-03-19 16:08
What file is being used to initialize the L58 run that is producing negative pbl_z?

**Comment by bstephens82** [comment] 2022-03-19 16:10
> What file is being used to initialize the L58 run that is producing negative pbl_z?

If you mean the ncdata file it's this one:
ncdata = '/glade/p/cesm/amwg_dev/juliob/cam_ic_files/se_dycore/FWsc_ne30pg3_58L_GRID_48_taperstart10km_lowtop_BL10_v3_beta1p75_Top_43km.nc'

**Comment by bstephens82** [comment] 2022-03-19 17:38
I did a little more digging and found that what is making `z` negative is that in [this line](https://github.com/ESCOMP/CAM/blob/4df7fa4fd02c2fed27e2495909ed8d56f29554d1/src/physics/cam/zm_conv.F90#L748), where z=zm+zs, `zs` is often negative, but sometimes it's larger in magnitude than `zm`, at least at this first timestep, hence `z` comes out negative.  `zs` being negative in turn derives from [`geos`](https://github.com/ESCOMP/CAM/blob/4df7fa4fd02c2fed27e2495909ed8d56f29554d1/src/physics/cam/zm_conv.F90#L740) being negative, and `geos` is fed into this subroutine as `state%phis`, so perhaps @adamrher's [comment above](https://github.com/ESCOMP/CAM/issues/543#issuecomment-1072875074) about PHIS is relevant to what's going on.

**Comment by adamrher** [comment] 2022-03-19 17:54
thanks Ben. Looking into where ```zi``` is coming from, it's an intent(in) variable from the main zm subroutine ```zm_convr```, and ```state%zi``` is the argument plopped into the subroutine call.

Question - is ```state%zi``` relative to the surface? Because ```z=zm+zs``` is not relative to the surface, it's the "ambient" elevation, or absolute elevation. It is true that zs < 0 in places, and so it's important for ```z``` and ```zi``` to either both be "ambient" or both be relative to the surface.

It seems to me the safer variable to use instead of ```zi``` is ```zf(i,pver+1) = zi(i,pver+1) + zs(i)``` which seems to indicate that ```zi``` is relative to the surface, and ```zf``` is the correct "ambient" elevation to be used.

I think we need to swap ```zf``` for ```zi```.

**Comment by JulioTBacmeister** [comment] 2022-03-19 19:00
PHIS should be coming from the ncdata file. Is it negative there?

**Comment by adamrher** [comment] 2022-03-19 19:13
> PHIS should be coming from the ncdata file. Is it negative there?

You know, it's actually not on the ncdata file Ben is using. It's also not on the cam.i file I suggested we use
```
/glade/scratch/hannay/archive/f.e21.FWscHIST.ne30_L48_BL10_cam6_3_041_control.hf.001/atm/hist/f.e21.FWscHIST.ne30_L48_BL10_cam6_3_041_control.hf.001.cam.i.1990-01-01-00000.nc
```

Which is a bit surprising to me. But tangential to this issue. The min/max PHIS/g from the ne30pg3 topo file is:
```
(0)	grab grids/uniform-res/ne30np4.pg3/topo/ne30pg3_nc3000_Co060_Fi001_PF_nullRR_Nsw042_20171014.nc
(0)	min PHIS/g -26.06648178610043
(0)	max PHIS/g 5169.736345371641
```

And so there are places below sea-level in ne30pg3 world (Death Valley comes to mind).

But I'm fairly certain the issue is as I stated in the previous post. ```z``` is absolute elevation, not height above the surface, and so can be negative. PBLH I think is relative to the surface, so instead of this:
```
      pbl_z(i) = z(i,nint(pblt(i)))
      parcel_ztop(i) = 0.5_r8*pbl_z(i) ! 0.5*Boundary layer top by default
```
we should swap ```z``` with ```zm```: 
```
      pbl_z(i) = zm(i,nint(pblt(i)))
      parcel_ztop(i) = 0.5_r8*pbl_z(i) ! 0.5*Boundary layer top by default
```
That ensures that the if statement ```if (zi(i,k+1)<= parcel_ztop(i)) then``` is always triggered and will prevent the divide by zero situation that occurs on when this if statement is not triggered.

**Comment by swrneale** [comment] 2022-03-19 19:29
Geesh, Saturday you guys :) I'll take a look later.

**Comment by PeterHjortLauritzen** [comment] 2022-03-19 19:42
state%zi and state%zm is relative to surface. It is computed from hydrostatic integral so if z goes negative either pressure is not monotonic or temperature is negative (see physics/cam/geopotential.F90). state%zi and state%zm are updated after each parameterization. Since we keep pressure fixed (and if it has been checked that the pressure going into physics is "physical"/monotonic) it would have to be T going negative.

Yes state%PHIS should have some negative values in it! So it could happen that state%phis+state%zm is negative even without non-monotonic pressure or negative T.

(remember to enjoy the nice weather on a weekend!)

**Comment by swrneale** [comment] 2022-03-21 13:19
So then, I think we should adjust
   pbl_z(i) = z(i,nint(pblt(i))) 
to be
   pbl_z(i) = zi(i,nint(pblt(i)))-zi(i,0)

Then it is guaranteed to be >= zero. 
pblt(i) has a maximum value of nlev whereas zi can got to nlev+1 (the surface). So actually pbl_z will always be at least half the thickness of the lowest level in this case.

@cacraigucar I will be on vacation most of this week and may not get to this, so maybe you can make this one line change for the commit?
Thanks all for tracking this down. The dangers of just developing in SCAM over the (not < sea level) ocean and without debugging on!

**Comment by bstephens82** [comment] 2022-03-21 15:05
I took a quick look at Rich's and Adam's proposed changes this morning and just wanted to clarify @swrneale that when you write zi(i,0) I'm guessing you really mean zi(i,59)?  Using zi(i,0) didn't compile since the compiler rejected the use of "0" as an index, and in any case I assume you want the bottom level of the model anyway which I think would be zi(i,59), right?  Using
~~~
pbl_z(i) = zi(i,nint(pblt(i)))-zi(i,59)
~~~
compiled and ran to completion (just a 2-hour run) with the debugger turned on.

Adam's proposed change of using pbl_z(i) = zm(i,nint(pblt(i))) also ran successfully with the debugger.

**Comment by swrneale** [comment] 2022-03-21 15:13
@bstephens82 yes of course sorry. Because it is an interface value variable then I think it should be zi since PBL is a thickness so zi(i,nlev+1) is the bottom interface - essentially g*phis. But to be honest there would be small differences and the 0.5 multiplying factor is somewhat arbitrary anyway.

**Comment by cacraigucar** [comment] 2022-03-21 15:19
@swrneale, @adamrher and @bstephens82 - It appears that we have two proposals on the table.  It sounds like perhaps we should adopt @swrneale's proposal, but I wanted to get consensus from the group.

**Comment by swrneale** [comment] 2022-03-21 15:33
@cacraigucar I don't think it really matters too much. I chose formulating in zi as the variable is already passed into the routine. So then it is a one line change.

**Comment by swrneale** [comment] 2022-03-21 16:24
Yep that makes sense. Probably need to define somethings like

pbl_z(i) = zi(i,nint(pblt(i)))-zi(i,nlev+1) 
Then
parcel_dztop(i) = 0.5_r8*pbl_z(i) ! 0.5*Boundary layer dz by default
parcel_ztop(i) = parcel_ztop(i)+zi(i,nlev+1) ! 0.5*Boundary layer z top by default (use for MSE)

Then it would be
 if (zi(i,k+1)<= parcel_dztop(i)) then ! Has to be relative to surface geo height.  

I may be able to implement this tomorrow, but I'm off on Spring Break!

**Comment by adamrher** [comment] 2022-03-21 16:32
> I may be able to implement this tomorrow, but I'm off on Spring Break!

I'm for taking our time and doing this right. So let's wait for Rich to find time. If it doesn't happen until next week that's fine by me. With the break I don't think we should expect much CAM7dev work this week. And Ben can just hack in the preliminary fixes for his experiments in the meantime, if he wants to run.

**Comment by JulioTBacmeister** [comment] 2022-03-21 17:41
That sounds fine to me, also.

**Comment by bstephens82** [comment] 2022-03-29 15:56
@swrneale just FYI I'm happy to create a PR for this issue if I know which fix to implement.

**Comment by adamrher** [comment] 2022-03-29 16:11
I think at the mtg this morning @gold2718 asked @jtruesdal to add this issue into the PR he has planned for https://github.com/ESCOMP/CAM/issues/551.

**Comment by swrneale** [comment] 2022-03-29 17:02
@jtruesdal Not quite there yet. Hope to finish it off tomorrow.

**Comment by swrneale** [comment] 2022-04-11 21:31
@jtruesdal @cecilehannay tested this configuration in CAM for 10 years and it looks good. I have tested in SCAM, and will check over everything there, but I think you should be able to do a PR with it then. I should get to this tomorrow.

**Comment by swrneale** [comment] 2022-04-14 21:26
The 1-month debug simulations completed without an issue.
The simulations look great with minimal changes in precipitation over the Oceans and favorable reductions over tropical orographic regions (East Africa, Andes, Maritime Continent). Overall tropical Rainfall RMSE compared to TRMM has improved from 2.22 to 1.99 in JJA, and 1.96 to 1.73 in DJF.

![image](https://user-images.githubusercontent.com/8239194/163477945-edb2bbba-0f7c-4c90-8b6f-66c8662a401f.png)

The distribution of the sub-convection daily temperature tendencies are also little effected by this bug fix follow the same PDF shift from the default L58 as seen previously. I think these changes are fine for a PR @jtruesdal 

![image](https://user-images.githubusercontent.com/8239194/163479612-216b28b6-9a02-4980-b829-2bbda30e0d01.png)

**Closed** 2022-05-16 23:50 UTC
Labels: bug
