### ISSUE TITLE
Need high-top version in cam_cesm2_1_rel

### ISSUE THREAD

**Issue by jedwards4b** [ESCOMP/CAM#642] opened 2022-08-22 21:10 UTC
### Issue Type

Infrastructure Update

### Issue Description

We have been using a branch at 
    hash = 9cae79d4950  
    repo_url = https://github.com/fvitt/CAM 
for an L83 version of the SMYLE project with our partners at Scripps institute.
We would like to add this to the branch in cam_cesm2_1_rel and include it in
cesm2.1.5-rc.01.    This is needed for documenting provenance of this experiment.
It could be another branch from the cam_cesm2_1_rel branch, but as long as there is no adverse affect on the lowtop model it doesn't seem necessary to do that.
@fvitt @nanr  

### Will this change answers?

No

### Will you be implementing this yourself?

No

**Comment by gold2718** [comment] 2022-08-24 17:25
Is this a duplicate of #529?

**Comment by jedwards4b** [comment] 2022-08-24 17:35
Yes, Sorry - I've closed #529.

**Closed** 2022-09-13 23:47 UTC
Labels: enhancement, BFB
