### ISSUE TITLE
Update MPAS-A physics, dynamics coupling with weak scaling changes

### ISSUE THREAD

**Issue by MiCurry** [ESCOMP/CAM#301] opened 2020-12-16 17:23 UTC
This issue serves as place to discuss (and perhaps for me to ask questions) replacing the current physics, dynamics coupling  with the changes proposed in PR #287 that address weak scaling issues (Issue #127). As well, it will serve as place to bring up any additional issues or changes that may appear when addressing this issue.

**Comment by MiCurry** [comment] 2020-12-16 17:36
At first I have a CAM developer/contributor question:

1. Are there any requirements that each commit of a PR has to make? Mainly:
    * I'm guessing each commit will need to compile successfully without errors (and warnings?). Are there any compilers I should use/test while developing? 
    * Do commits need to run successfully or pass regression tests? Would it be okay to have a commit that compiles, but doesn't run successfully (Knowing, of course, that the combinations of all commits of a PR will successfully run)?

**Comment by cacraigucar** [comment] 2020-12-16 17:54
The details for submitting code to the CAM repo are in the ESCOMP/CAM wiki.  Specifically: https://github.com/ESCOMP/CAM/wiki/CAM-Development-Workflow-in-GitHub#how-to-submit-code-changes-to-be-included-in-escompcam

The compilers CAM tests with are PGI and NAG (on izumi) and intel on cheyenne.

The code you submit must compile and not break any of the existing tests.  The CAM SE assigned to your PR will run all the CAM regression tests to verify this.  It is best if the new code runs without crashing, though the answers may need to be tuned or expanded upon with future PRs.

**Comment by gold2718** [comment] 2020-12-16 18:11
In addition to the documented procedures, we generally do not have many rules here, mostly because we have different development styles.

My approach is:

1. During development, commit early and commit often. This enables experimentation, comparison, and easy recovery. Because this is on a branch in your CAM Fork, you should use the tools to enhance your workflow.
2. At least once before opening a PR (usually when updating to a more recent CAM tag), I rebase (interactive) to the head of cam_development. I use this as an opportunity to clean up my commit history to reflect the logical progress on my project. At this point, I have only run a few, targeted tests and the remaining commit messages will mention them. Often, this might be one big commit when things are working or mostly working.
3. It is helpful to run at least the Izumi Nag and PGI tests before opening a PR.
4. After opening a PR, you MAY **NOT** rebase.
5. Finally, if you are asked to add an unrelated bug fix or other minor change to your PR, that change must be in its own commit.

I regard the last three as general rules, the rest represent my workflow.

**Comment by MiCurry** [comment] 2020-12-16 18:39
Thanks for the links and tips @cacraigucar  and @gold2718. All projects seem to do things a little bit differently, even across NCAR, so its nice to make sure we're on the same page before I make the PR. Thanks!

**Comment by gold2718** [comment] 2022-04-29 18:08
I think this was done in #303, however, the formatting above was not correct.

**Closed by gold2718** 2022-04-29 18:08 UTC
Labels: enhancement
