### ISSUE TITLE
Failing beta test: ERP_D_Ln9.f09_f09_mg17.FSD.cheyenne_intel.cam-outfrq9s_contrail

### ISSUE THREAD

**Issue by cacraigucar** [ESCOMP/CAM#463] opened 2021-11-09 19:16 UTC
This first appeared in April in CESM testing (but fell through the cracks).  Since this was shortly after cam6_3_014 was committed, I suspect that the error crept in then.  

According to Chris the error message is:
297:MPT ERROR: Rank 297(g:297) received signal SIGFPE(8).
297:    Process ID: 12632, Host: r7i1n2, Program: /glade/scratch/fischer/t/cesm2_3_alpha07a_alpha_intel_mct/ERP_D_Ln9_Vmct.f09_f09_mg17.FSD.cheyenne_intel.cam-outfrq9s_contrail.GC.c2_3_a07a_int/bld/cesm.exe
297:    MPT Version: HPE MPT 2.22  03/31/20 15:59:10
297:
297:MPT: --------stack traceback-------
297:OMP: Warning #190: Forking a process while a parallel region is active is potentially unsafe.

This will need investigation to track down what is happening.

**Comment by gold2718** [comment] 2021-11-24 18:29
This is a duplicate of #362

**Closed by gold2718** 2021-11-24 18:29 UTC
