### ISSUE TITLE
Invalid % character in namelist_defaults_cam.xml

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CAM#230] opened 2020-09-24 20:59 UTC
In these lines:

https://github.com/ESCOMP/CAM/blob/af4623ffd3cb14408cc032832fd483b5c18262e3/bld/namelist_files/namelist_defaults_cam.xml#L2066-L2077

the `%` character is invalid in xml.

@jrya7 and @oneilljo-ncar ran into this issue when trying to generate the documentation for the CESM2.2 release. This doesn't need to be resolved for the CESM2.2.0 release (they can just have changes in their sandbox for now), but should be resolved longer-term.

**Comment by gold2718** [comment] 2020-09-24 21:07
This is not a bug as far as CAM is concerned as it is proper namelist syntax
If you are having trouble with the namelist to documentation software, remove these entries or convert % to something else.
This will be fixed when we move to the new namelist format.

**Closed by gold2718** 2020-09-24 21:07 UTC

**Comment by billsacks** [comment] 2020-09-24 21:13
But it's invalid xml. Try opening the file in emacs, for example. See attached screen shot.

<img width="2032" alt="Screen Shot 2020-09-24 at 3 12 11 PM" src="https://user-images.githubusercontent.com/6266741/94200860-5f805d00-fe78-11ea-8c55-52dd8f8e50eb.png">

**Comment by gold2718** [comment] 2020-09-24 21:17
Again, not a bug as far as CAM is concerned as it does not use any XML validation on this file.
We have been aware of this situation for a long time (since SILHS was put in).
