### ISSUE TITLE
High vertical resolution crashes (second round)

### ISSUE THREAD

**Issue by JulioTBacmeister** [ESCOMP/CAM#297] opened 2020-12-14 23:44 UTC
Problem has been narrowed to point on coastline of Iran/Paksitan.  Atmospheric model sensible heat flux timestep output has NaN.  Point is 0.99+ land but has ocean fraction as well.  While SHFLX in atmosphere is NaN, sensible heat flux from land to coupler is finite (-5 Wm-2)

**Comment by cecilehannay** [comment] 2020-12-15 01:47
The model crashes in the same area in SE and FV although there are some
differences:

SE: /glade/scratch/hannay/f.e21.ne30_L48_BL10_native_hf/run
- the model crashes after 6 months (june 1979 at 54000s)
- the location is lat=27.3313/lon=57.5
- This grid box is 99.3% land and 0.7% ocean.

FV: /glade/scratch/hannay/f.e21.f09_L48_BL10_native_hf/run
- the model crashes after 20 months (Sep 1980 at 34200s)
- the location is lat=26.8586/lon=55
- This grid box is 61.8% land and 38.2% ocean.



+++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Cecile Hannay
National Center for Atmospheric Research
email: hannay@ucar.edu
webpage: http://www.cgd.ucar.edu/staff/hannay/

"Live as if you were to die tomorrow. Dream as if you were to live
forever."
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by cecilehannay** [comment] 2020-12-15 15:18
This is a plot of TS and TBOT from Isla.

[image: Screen Shot 2020-12-15 at 8.16.14 AM.png]

**Comment by JulioTBacmeister** [comment] 2020-12-26 17:33
Conditions for crash appear to be hot dry atmosphere over warm sea surface coupled with low surface winds.  See attached plot
![image](https://user-images.githubusercontent.com/9221710/103156421-a3c81580-4765-11eb-8262-fe2462ad8db2.png)

**Comment by swrneale** [comment] 2020-12-28 16:40
@JulioTBacmeister does this imply that the model does not crash in response to most U10<0 (black points)? I guess I'm confused. Just as note of what we looked at during the Lab. Sea. crisis (crises?). This plot has the number of iterations this calculation takes (on average and the maximum#). And it does frequently struggle to converge frequently but mostly over ice it seems.  
![image](https://user-images.githubusercontent.com/8239194/103229606-a30fba80-48f0-11eb-86c4-2b1db5d74ffd.png)

**Comment by JulioTBacmeister** [comment] 2020-12-28 17:32
No. The model probably can't survive u10m<0 in shr_flux_atmocn since this will generate NaN's in the surface fluxes sent back from the coupler.

My plot was constructed from an offline IDL "unit test" of shr_flux_atmocn.  It iterates 10 times.  I then look for NaN's in ustar using IDL's "finite()" function.  Black shows where finite(ustar)=0.  The large filled black and white circles are simply overplotted using thbot, qbot and ts saved from the full CAM FV and SE runs at the Pakistan/Iran crash locations.

The IDL unit test is initialized on 500x500 grid of thbot and qbot values chosen so that the air-sea differences "tdiff" and "qdiff" at the start of the atmocn iteration includes the crash values.  These are calculated as

tdiff(n)=thbot(n)-ts(n)
qdiff(n)=qbot(n)-ssq(n)

where ssq(n) is the saturation specific humidity at the surface; ssq(n)=qsat( ts(n) ), calculated using shr_flux_atmocn's local qsat function.

Note that the IDL unit test produces identical results to full CAM when initialized with the actual CAM inputs to shr_flux_atmocn output at the crash times and locations

**Comment by JulioTBacmeister** [comment] 2020-12-28 17:51
P.S.  I think our previous experience with 32L CAM may not have sampled the conditions that can appear in these coastal desert points with thin lowest layers and ZM on.  Even with thin layers and ZM on the "bad" points are a sparse subset.  If we weren't generating strongly negative qdiff before, the likelihood of hitting one of these points is small.  This is simple enough to check - I just haven't gotten around to it.

**Comment by swrneale** [comment] 2020-12-28 18:47
So how do you think U10m is going wrong, and is it a function of the fact that the lowest model level is precariously close to 10m? I am guessing  rd   = rdn / (1.0_R8 + rdn/loc_karman*(alz-psimh)) goes -ve as alz-psimh is negative in very unstable regimes.

**Comment by JulioTBacmeister** [comment] 2020-12-28 19:29
That's exactly right.  The iteration is failing because the denominator in 

rd = rdn / (1.0_R8 + rdn/loc_karman*(alz-psimh)) 

becomes negative.  Increasing alz by setting zref=5.0m for example would also fix the problem according to the IDL unit test.

**Comment by swrneale** [comment] 2020-12-28 20:03
I think LP depends on it being 10m yes. I messed with making the ref level be 5 m (in L256 resolution which is about 9m for the lowest level). It isn't that sensitive in SCAM, esp for L256. Fluxes are way more sensitive to the vertical resolution (for TOGA IOP). And the Zheng scheme is quite different for LHFLX. Would be good to look at Cecile's CAM runs for this. 

![image](https://user-images.githubusercontent.com/8239194/103240243-04458700-490d-11eb-8bb1-ffdfb65aab82.png)

![image](https://user-images.githubusercontent.com/8239194/103240248-09a2d180-490d-11eb-94a0-05d3c3fd99a7.png)

**Comment by adamrher** [comment] 2021-01-05 19:27
I wonder what the pbl depth is at these ill points. It's mixed with desert so I with think pretty low? If it's at one of the lowest levels than that is an extremely small upper limit for the subcloud layer in zm.

**Comment by gold2718** [comment] 2021-01-11 16:49
@JulioTBacmeister, @swrneale, @cecilehannay, @adamrher:
Any update on this? Has a fix (and fix implementer) been decided?

**Comment by JulioTBacmeister** [comment] 2021-01-11 16:52
Fix implementer is Cecile/Julio.  Least intrusive fix suggested by Bill
Large is being tested. Don't know if results are in.

**Comment by gold2718** [comment] 2021-01-11 18:41
Is the change in the CAM code or the coupler?

**Comment by JulioTBacmeister** [comment] 2021-01-11 18:42
It is in shr_flux_mod.F90

**Comment by gold2718** [comment] 2021-01-11 18:47
Then a CIME issue should be opened and this issue should be closed (with a reference to the new CIME issue).

**Comment by cecilehannay** [comment] 2021-01-14 22:35
I am moving the issue into the CIME repo:
https://github.com/ESMCI/cime/issues/3826

**Comment by cacraigucar** [comment] 2021-06-01 21:04
@jedwards4b provided in a meeting today, a link to a branch on his cime fork which should fix this issue.  It is:

https://github.com/jedwards4b/cime/tree/shr_flux_limit_fix

There was discussion that this may impact CAM in cases other than high vertical resolution runs.  We will run regression tests using this change and see what impacts it may have.

**Comment by adamrher** [comment] 2022-02-01 16:58
I think this issue should have been closed when we brought in the shr_flux_mod mods in the new CESM_SHARE directory ... (it has subsequently been moved into cmeps).

@cacraigucar I have an email from you saying "It looks like the original shr_flux_mod changes were brought in in cesm2_3_alpha07a" ... can we close this then?

**Comment by adamrher** [comment] 2022-09-14 16:09
should this issue be closed?

**Comment by cacraigucar** [comment] 2022-09-14 16:16
Yes, thanks for pointing this out.  The cime issue which addressed this (ESMCI/cime#3826) was closed January, 2021

**Closed by cacraigucar** 2022-09-14 16:16 UTC
Labels: Priority 1 bug
