### ISSUE TITLE
Incorrect error message

### ISSUE THREAD

**Issue by jedwards4b** [ESCOMP/CAM#911] opened 2023-11-13 17:12 UTC
### What happened?

If you run ne30pg3_t232.BLT1850_v0c without cosp but add variables such as 
 
 ```
FLDLST: Uzm in fincl(1, 5) only available with FV dycore
 FLDLST: Vzm in fincl(2, 5) only available with FV dycore
 FLDLST: Wzm in fincl(3, 5) only available with FV dycore
 FLDLST: THzm in fincl(4, 5) only available with FV dycore
 FLDLST: VTHzm in fincl(5, 5) only available with FV dycore
 FLDLST: WTHzm in fincl(6, 5) only available with FV dycore
 FLDLST: UVzm in fincl(7, 5) only available with FV dycore
 FLDLST: UWzm in fincl(8, 5) only available with FV dycore
```
To user_nl_cam - the error message "only available with FV dycore" is incorrect.   The correct message should be that -cosp needs to be added to CAM_CONFIG_OPTS.  

### What are the steps to reproduce the bug?

Create a case in cesm2_3_alpha16g using 
 --res ne30pg3_t232 --compset BLT1850_v0c 
and add these variables to user_nl_cam 
if -cosp is included it works fine, otherwise you get the error above.

### What CAM tag were you using?

cesm2_3_alpha16g (cam6_3_132)

### What machine were you running CAM on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

Intel

### Will you be addressing this bug yourself?

Any CAM SE can do this

**Comment by cacraigucar** [comment] 2023-11-14 23:18
Duplicate of #863  - closing

**Closed** 2023-11-14 23:19 UTC
Labels: bug, CoupledEval3
