### ISSUE TITLE
Increase PE layout for MT runs

### ISSUE THREAD

**Issue by cacraigucar** [ESCOMP/CAM#812] opened 2023-05-19 23:04 UTC
`###` Issue Type

Infrastructure Update

### Issue Description

MT runs out-of-the-box error out while writing restart files.

@tilmes reported that the following PE layout worked for her and preliminary testing indicates it does solve the problem:

```
</entry>
    <entry id="NTASKS">
      <type>integer</type>
      <values>
        <value compclass="ATM">-50</value>
        <value compclass="CPL">-50</value>
        <value compclass="OCN">-50</value>
        <value compclass="WAV">1</value>
        <value compclass="GLC">1</value>
        <value compclass="ICE">-50</value>
        <value compclass="ROF">-50</value>
        <value compclass="LND">-50</value>
        <value compclass="ESP">1</value>
      </values>
      <desc>number of tasks for each component</desc>
    </entry>
    <entry id="NTASKS_PER_INST">
      <type>integer</type>
      <values>
        <value compclass="ATM">1800</value>
        <value compclass="OCN">1800</value>
        <value compclass="WAV">1</value>
        <value compclass="GLC">1</value>
        <value compclass="ICE">1800</value>
        <value compclass="ROF">1800</value>
        <value compclass="LND">1800</value>
        <value compclass="ESP">1</value>
      </values>
      <desc>Number of tasks per instance for each component. DO NOT EDIT: Set automatically by case.setup based on NTASKS, NINST and MULTI_DRIVER</desc>
    </entry>
    <entry id="NTHRDS">
      <type>integer</type>
      <values>
        <value compclass="ATM">1</value>
        <value compclass="CPL">1</value>
        <value compclass="OCN">1</value>
        <value compclass="WAV">1</value>
        <value compclass="GLC">1</value>
        <value compclass="ICE">1</value>
        <value compclass="ROF">1</value>
        <value compclass="LND">1</value>
        <value compclass="ESP">1</value>
      </values>
      <desc>number of threads for each task in each component</desc>
    </entry>


```
### Will this change answers?

No

### Will you be implementing this yourself?

Any CAM SE can do this

**Comment by jedwards4b** [comment] 2023-07-10 22:42
This problem can be addressed by reducing the PIO_BUFFER_SIZE_LIMIT xml variable.   The default value of 134217728 is too large for this case running on 
4 nodes of cheyenne.   Changing to ./xmlchange PIO_BUFFER_SIZE_LIMIT=17108864 causes the test to pass.

**Comment by cacraigucar** [comment] 2023-07-10 23:09
> This problem can be addressed by reducing the PIO_BUFFER_SIZE_LIMIT xml variable. The default value of 134217728 is too large for this case running on 4 nodes of cheyenne. Changing to ./xmlchange PIO_BUFFER_SIZE_LIMIT=17108864 causes the test to pass.

@jedwards4b - Thanks for the info - I would never have figured this out!  Is there a "proper" way to set this for all compsets which use "MT" (both HIST and 1850) in the config_component.xml?  I'm not sure how to set xmlchange variables at the "high level"

**Comment by tilmes** [comment] 2023-07-11 12:11
Thanks for keeping me on this discussion. I am wondering about the Bergso variable that seems to be a troublemaker? If so, would it be useful to check if there is a scientific problem with it? I am not sure if I understand the conclusions or whether this is just a symptom or if the variable is the problem,
thanks Simone

**Comment by jedwards4b** [comment] 2023-07-11 13:47
We should be able to set it for a given compset and machine in config_pio.xml, 
I will test that today and let you know.

**Comment by adamrher** [comment] 2023-07-11 15:22
For my sanity, does it make sense that we need to lower the ```PIO_BUFFER_SIZE_LIMIT```? MT is only L93 levels; we have much bigger vertical grids that run w/o having the change this pio buffer size, right? So why MT?

**Comment by jedwards4b** [comment] 2023-07-11 15:24
Do we?   Are we testing these on 4 cheyenne nodes or are they already using many more nodes by default?

**Comment by adamrher** [comment] 2023-07-12 15:03
Do waccm cases (L70) run out of the box? How many nodes are the default for FW compsets?

**Comment by jedwards4b** [comment] 2023-07-12 15:16
https://github.com/ESCOMP/CAM/blob/cam_development/cime_config/config_pes.xml#L334

Or you could try setting up a case yourself and answer these questions.

**Comment by adamrher** [comment] 2023-07-12 16:35
I can confirm that FWHIST out of the box (w/ ne30pg3) defaults to the pe layout at the top of this thread, that Simone found resolves the MT issue. That is, the default for L70/ne30pg3 is 1800 tasks, or 50 nodes. @tilmes is this how you found the pe layout that worked?

**Comment by tilmes** [comment] 2023-07-14 15:49
Yes, probably, I took that from the WACCM compset, Simone

**Comment by peverwhee** [comment] 2023-07-17 16:02
@jedwards4b were you able to test your change to config_pio.xml? If so, can you post that change here so I can get a ccs_config tag made? Thanks!

**Comment by jedwards4b** [comment] 2023-07-17 16:04
@peverwhee I was able to test it however results were mixed, it works sometimes but not always.

**Comment by peverwhee** [comment] 2023-07-17 16:08
@jedwards4b How fun. I'm sure you're swamped - can you post the change so one of us can take up the mantle and try to debug?

**Comment by peverwhee** [comment] 2023-07-17 16:19
@jedwards4b thanks Jim. I suppose I could've just looked up higher in the discussion for that.

**Comment by peverwhee** [comment] 2023-07-17 17:07
@jedwards4b one more question - how many nodes were you using for your tests? 4? 8?

**Comment by jedwards4b** [comment] 2023-07-17 17:08
8 nodes on cheyenne

**Closed** 2023-08-23 20:06 UTC
Labels: CoupledEval2
